name: Multiplatform build & push

on:
  push:
    branches: ["main"]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: reraw
  VERSION: latest
  TAG: ${{ github.ref_name }}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        go-version: ["1.24.x"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      #- name: Install Go
      #  uses: actions/setup-go@v5
      #  with:
      #    go-version-file: "./go.mod"

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      #- name: Run tests
      #  run: go test -v ./...

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test

      - name: Docker build
        if: github.actor != 'dependabot[bot]'
        uses: mr-smithers-excellent/docker-build-push@v6
        id: build
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          registry: ${{ env.REGISTRY }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: ${{ startsWith(github.ref, 'refs/tags/v') }}
          buildArgs: TAG=${{ env.TAG }}
